### ISSUE TITLE
MS2Create 1.1 generates different sized file and/or does not work and/or re-extract properly compared to 1.0

### ISSUE THREAD

**Issue by Etchavious** [Miyuyami/MS2Tools#5]
I've been using 1.0 for a while now and grabbed a new copy since I just built a new PC. I still have my old build of 1.0 on my platform, and I've been doing some testing with 1.1. I know multiple crypto changes were made with the rework back in September 2020. I'm not sure if I'm missing something on my platform, or if there's an underlying issue. This issue strictly appears to be a problem with MS2Create, not MS2Extract.

I started with a known good extracted Xml directory. I created a m2d via version 1.0 and 1.1. Size differences are below.

1.0 - m2d (96,333,184 bytes) | m2h (1,417,964 bytes)
1.1 - m2d (96,222,336 bytes) | m2h (1,431,076 bytes)

output.log run from debug logging is identical on both versions.

I then proceeded to extract the m2d/m2h pair on 1.0 and 1.1 respectively within their directories. I was able to extract with both versions 1.0 and 1.1 MS2Extract on the 1.0 file and everything was successful. When I try to extract the 1.1 file with either the 1.0 or the 1.1 MS2Extract file, I have the following issues below:

**The 1.0 MS2Extract program throws an error at this point:** 

[Info] [1/8/2021 10:11:08 PM] Extracting file "effect/npc/skill/papulatus/papulatusmod/eff_papulatus_attack_03_a_power_mod.xml", "850 B". (69907/69909)
[Info] [1/8/2021 10:11:08 PM] Extracting file "effect/npc/skill/papulatus/papulatusmod/eff_papulatus_blockdrop_mod.xml", "1.833 KiB". (69908/69909)
[Info] [1/8/2021 10:11:08 PM] Extracting file "effect/npc/skill/papulatus/papulatusmod/eff_papulatus_mod_hit_01.xml", "1.688 KiB". (69909/69909)
[Error] [1/8/2021 10:11:11 PM] System.AggregateException: One or more errors occurred. ---> System.Runtime.InteropServices.SEHException: External component has thrown an exception.
   at MS2Lib.NativeMethods.Decrypt64(Byte[] src, UIntPtr srcSize, Byte[] dst, UIntPtr dstSize, Byte[] key, UIntPtr keySize, Byte[] iv)
   at MS2Lib.Decryption.Decrypt(Byte[] src, UInt32 dstSize, Byte[] key, Byte[] iv)
   at MS2Lib.CryptoHelper.Decrypt(MS2CryptoMode cryptoMode, Byte[] src, UInt32 compressedSize, UInt32 size)
   at MS2Lib.CryptoHelper.<>c__DisplayClass2_0.<DecryptDataToDataAsync>b__0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at MS2Lib.CryptoHelper.<DecryptDataToDataAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at MS2Lib.CryptoHelper.<DecryptStreamToDataAsync>d__1.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at MS2Lib.CryptoHelper.<>c.<DecryptStreamToStreamAsync>b__0_0(Task`1 t)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at MS2Lib.MS2File.<GetDecryptedStreamAsync>d__28.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at MS2Extract.Program.<ExtractFileAsync>d__17.MoveNext() in C:\Users\etch\Downloads\MS2Tools-master\MS2Tools-master\MS2Extract\Program.cs:line 195
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at MS2Extract.Program.<ExtractArchiveAsync>d__15.MoveNext() in C:\Users\etch\Downloads\MS2Tools-master\MS2Tools-master\MS2Extract\Program.cs:line 166
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at MS2Extract.Program.<ExtractArchivesInDirectoryAsync>d__12.MoveNext() in C:\Users\etch\Downloads\MS2Tools-master\MS2Tools-master\MS2Extract\Program.cs:line 118
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at MS2Extract.Program.<RunAsync>d__11.MoveNext() in C:\Users\etch\Downloads\MS2Tools-master\MS2Tools-master\MS2Extract\Program.cs:line 79
---> (Inner Exception #0) System.Runtime.InteropServices.SEHException (0x80004005): External component has thrown an exception.
   at MS2Lib.NativeMethods.Decrypt64(Byte[] src, UIntPtr srcSize, Byte[] dst, UIntPtr dstSize, Byte[] key, UIntPtr keySize, Byte[] iv)
   at MS2Lib.Decryption.Decrypt(Byte[] src, UInt32 dstSize, Byte[] key, Byte[] iv)
   at MS2Lib.CryptoHelper.Decrypt(MS2CryptoMode cryptoMode, Byte[] src, UInt32 compressedSize, UInt32 size)
   at MS2Lib.CryptoHelper.<>c__DisplayClass2_0.<DecryptDataToDataAsync>b__0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at MS2Lib.CryptoHelper.<DecryptDataToDataAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at MS2Lib.CryptoHelper.<DecryptStreamToDataAsync>d__1.MoveNext()<---

**The 1.1 MS2Extract program throws an error at this point:** 

[Info   ] [2021-01-08T22:11:36.6150573Z] Extracting file "effect/npc/skill/papulatus/papulatusmod/eff_papulatus_attack_03_a_power_mod.xml", "850 B". (69907/69909)
[Info   ] [2021-01-08T22:11:36.6151200Z] Extracting file "effect/npc/skill/papulatus/papulatusmod/eff_papulatus_blockdrop_mod.xml", "1.833 KiB". (69908/69909)
[Info   ] [2021-01-08T22:11:36.6151823Z] Extracting file "effect/npc/skill/papulatus/papulatusmod/eff_papulatus_mod_hit_01.xml", "1.688 KiB". (69909/69909)
[Error  ] [2021-01-08T22:11:36.6509256Z] System.IO.IOException: invalid characters encountered in base64 data
   at Org.BouncyCastle.Utilities.Encoders.Base64Encoder.Decode(Byte[] data, Int32 off, Int32 length, Stream outStream) in /_/crypto/src/util/encoders/Base64Encoder.cs:line 167
   at MS2Lib.CryptoHelper.GetDecryptionStreamAsync(Stream input, IMS2SizeHeader size, IMultiArray key, IMultiArray iv, Boolean zlibCompressed) in C:\Users\Etch\source\repos\MS2Tools\MS2Lib\MS2Lib\Cryptography\CryptoHelper.cs:line 24
   at MS2Lib.NS2F.CryptoRepositoryNS2F.GetDecryptionStreamAsync(Stream input, IMS2SizeHeader size, Boolean zlibCompressed) in C:\Users\Etch\source\repos\MS2Tools\MS2Lib\MS2Lib\CryptoRepository\NS2F\CryptoRepositoryNS2F.cs:line 21
   at MS2Extract.Program.ExtractFileAsync(String destinationPath, IMS2File file) in C:\Users\Etch\source\repos\MS2Tools\MS2Extract\Program.cs:line 187
   at MS2Extract.Program.ExtractArchiveAsync(String headerFile, String dataFile, String destinationPath) in C:\Users\Etch\source\repos\MS2Tools\MS2Extract\Program.cs:line 163
   at MS2Extract.Program.ExtractArchivesInDirectoryAsync(String sourcePath, String destinationPath) in C:\Users\Etch\source\repos\MS2Tools\MS2Extract\Program.cs:line 118
   at MS2Extract.Program.RunAsync(String[] args) in C:\Users\Etch\source\repos\MS2Tools\MS2Extract\Program.cs:line 79

This tells me that during the creation of the archive file(s), something must be failing somewhere and not recording on the log.

According to a successful extraction, the eff_papulatus_mod_hit_01.xml file should actually be at position 19885/69909, so it's also reordering when it's building the file, I'm not sure if this information is relevant at all. I can provide my files for research if required, and I'll continue to poke around and figure out if I can identify anything on my end, but this is the current use case I've found with using version 1.1 of MS2Create.

**Comment by Etchavious** [comment]
Additionally, this issue occurs from my own compiled version as well as your released version. I saw a previous post with a similar problem, so I just tested, and it's still having the same issue.

I also took a hex editor to the m2d file and beyond line 00E9A30 it's just null data filling up the file.

Thanks!

**Comment by Miyuyami** [comment]
I made an update. I think it should fix your issue.
If the issue still happens in 1.1.1 please reopen it.
